# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 18:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowsingActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(default='', max_length=45)),
                ('date_time', models.DateTimeField()),
                ('path', models.CharField(max_length=1000)),
                ('referrer', models.CharField(default='', max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='SessionInfo',
            fields=[
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sessions.Session')),
                ('user_agent', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='browsingactivity',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.Session'),
        ),
        migrations.AddField(
            model_name='browsingactivity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
